name: "Release aopi"

on:
  workflow_run:
    workflows: ["Pre-commit check"]
    branches: [master]
    types: [completed]

jobs:
  publisher:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12'

      - name: Set up Python 🏗
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install python dependencies 👨🏻‍💻
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false

      - name: Install yarn dependencies 👨🏻‍💻
        run: yarn --cwd aopi-frontend/

      - name: Build aopi-frontend 🛠
        run: yarn --cwd aopi-frontend/ generate

      - name: Release package 🎉🎊🥳🎊🎉
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
